name: Reusable Build

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "22"
    app-name:
      required: true
      type: string
    secrets:
      NEXT_PUBLIC_CART_SERVICE_URL:
        required: true
      NEXT_PUBLIC_ORDERS_SERVICE_URL:
        required: true
      NEXT_PUBLIC_PRODUCTS_SERVICE_URL:
        required: true
      NEXT_PUBLIC_REVIEW_SERVICE_URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npx turbo run build --filter=${{ inputs['app-name'] }}...
        env:
          NEXT_PUBLIC_CART_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_CART_SERVICE_URL }}
          NEXT_PUBLIC_ORDERS_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_ORDERS_SERVICE_URL }}
          NEXT_PUBLIC_PRODUCTS_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_PRODUCTS_SERVICE_URL }}
          NEXT_PUBLIC_REVIEW_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_REVIEW_SERVICE_URL }}
